#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroFour.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Corto1BD23")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSemestre(Semestre instance);
    partial void UpdateSemestre(Semestre instance);
    partial void DeleteSemestre(Semestre instance);
    partial void InsertCurso(Curso instance);
    partial void UpdateCurso(Curso instance);
    partial void DeleteCurso(Curso instance);
    partial void InsertCarrera(Carrera instance);
    partial void UpdateCarrera(Carrera instance);
    partial void DeleteCarrera(Carrera instance);
    partial void InsertAsigna_Curso(Asigna_Curso instance);
    partial void UpdateAsigna_Curso(Asigna_Curso instance);
    partial void DeleteAsigna_Curso(Asigna_Curso instance);
    partial void InsertAlumno(Alumno instance);
    partial void UpdateAlumno(Alumno instance);
    partial void DeleteAlumno(Alumno instance);
    #endregion
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Semestre> Semestres
		{
			get
			{
				return this.GetTable<Semestre>();
			}
		}
		
		public System.Data.Linq.Table<Municipio> Municipios
		{
			get
			{
				return this.GetTable<Municipio>();
			}
		}
		
		public System.Data.Linq.Table<Departamento> Departamentos
		{
			get
			{
				return this.GetTable<Departamento>();
			}
		}
		
		public System.Data.Linq.Table<Curso> Cursos
		{
			get
			{
				return this.GetTable<Curso>();
			}
		}
		
		public System.Data.Linq.Table<Carrera> Carreras
		{
			get
			{
				return this.GetTable<Carrera>();
			}
		}
		
		public System.Data.Linq.Table<Asigna_Curso> Asigna_Cursos
		{
			get
			{
				return this.GetTable<Asigna_Curso>();
			}
		}
		
		public System.Data.Linq.Table<Alumno> Alumnos
		{
			get
			{
				return this.GetTable<Alumno>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Semestre")]
	public partial class Semestre : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Semestre;
		
		private string _Nombre_Semestre;
		
		private EntitySet<Curso> _Cursos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_SemestreChanging(int value);
    partial void OnId_SemestreChanged();
    partial void OnNombre_SemestreChanging(string value);
    partial void OnNombre_SemestreChanged();
    #endregion
		
		public Semestre()
		{
			this._Cursos = new EntitySet<Curso>(new Action<Curso>(this.attach_Cursos), new Action<Curso>(this.detach_Cursos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Semestre", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Semestre
		{
			get
			{
				return this._Id_Semestre;
			}
			set
			{
				if ((this._Id_Semestre != value))
				{
					this.OnId_SemestreChanging(value);
					this.SendPropertyChanging();
					this._Id_Semestre = value;
					this.SendPropertyChanged("Id_Semestre");
					this.OnId_SemestreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Semestre", DbType="NVarChar(50)")]
		public string Nombre_Semestre
		{
			get
			{
				return this._Nombre_Semestre;
			}
			set
			{
				if ((this._Nombre_Semestre != value))
				{
					this.OnNombre_SemestreChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Semestre = value;
					this.SendPropertyChanged("Nombre_Semestre");
					this.OnNombre_SemestreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Semestre_Curso", Storage="_Cursos", ThisKey="Id_Semestre", OtherKey="Id_Semestre")]
		public EntitySet<Curso> Cursos
		{
			get
			{
				return this._Cursos;
			}
			set
			{
				this._Cursos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cursos(Curso entity)
		{
			this.SendPropertyChanging();
			entity.Semestre = this;
		}
		
		private void detach_Cursos(Curso entity)
		{
			this.SendPropertyChanging();
			entity.Semestre = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Municipio")]
	public partial class Municipio
	{
		
		private System.Nullable<int> _Codigo_Municipio;
		
		private string _Municipio1;
		
		private System.Nullable<int> _Codigo;
		
		public Municipio()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo_Municipio", DbType="Int")]
		public System.Nullable<int> Codigo_Municipio
		{
			get
			{
				return this._Codigo_Municipio;
			}
			set
			{
				if ((this._Codigo_Municipio != value))
				{
					this._Codigo_Municipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Municipio", Storage="_Municipio1", DbType="NVarChar(150)")]
		public string Municipio1
		{
			get
			{
				return this._Municipio1;
			}
			set
			{
				if ((this._Municipio1 != value))
				{
					this._Municipio1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int")]
		public System.Nullable<int> Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departamento")]
	public partial class Departamento
	{
		
		private System.Nullable<int> _Codigo;
		
		private string _Departamento1;
		
		public Departamento()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int")]
		public System.Nullable<int> Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Departamento", Storage="_Departamento1", DbType="NVarChar(150)")]
		public string Departamento1
		{
			get
			{
				return this._Departamento1;
			}
			set
			{
				if ((this._Departamento1 != value))
				{
					this._Departamento1 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Curso")]
	public partial class Curso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id_Curso;
		
		private string _Nombre_Curso;
		
		private int _Creditos_Curso;
		
		private string _Id_Carrera;
		
		private int _Id_Semestre;
		
		private EntitySet<Asigna_Curso> _Asigna_Cursos;
		
		private EntityRef<Semestre> _Semestre;
		
		private EntityRef<Carrera> _Carrera;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_CursoChanging(string value);
    partial void OnId_CursoChanged();
    partial void OnNombre_CursoChanging(string value);
    partial void OnNombre_CursoChanged();
    partial void OnCreditos_CursoChanging(int value);
    partial void OnCreditos_CursoChanged();
    partial void OnId_CarreraChanging(string value);
    partial void OnId_CarreraChanged();
    partial void OnId_SemestreChanging(int value);
    partial void OnId_SemestreChanged();
    #endregion
		
		public Curso()
		{
			this._Asigna_Cursos = new EntitySet<Asigna_Curso>(new Action<Asigna_Curso>(this.attach_Asigna_Cursos), new Action<Asigna_Curso>(this.detach_Asigna_Cursos));
			this._Semestre = default(EntityRef<Semestre>);
			this._Carrera = default(EntityRef<Carrera>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Curso", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id_Curso
		{
			get
			{
				return this._Id_Curso;
			}
			set
			{
				if ((this._Id_Curso != value))
				{
					this.OnId_CursoChanging(value);
					this.SendPropertyChanging();
					this._Id_Curso = value;
					this.SendPropertyChanged("Id_Curso");
					this.OnId_CursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Curso", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre_Curso
		{
			get
			{
				return this._Nombre_Curso;
			}
			set
			{
				if ((this._Nombre_Curso != value))
				{
					this.OnNombre_CursoChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Curso = value;
					this.SendPropertyChanged("Nombre_Curso");
					this.OnNombre_CursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creditos_Curso", DbType="Int NOT NULL")]
		public int Creditos_Curso
		{
			get
			{
				return this._Creditos_Curso;
			}
			set
			{
				if ((this._Creditos_Curso != value))
				{
					this.OnCreditos_CursoChanging(value);
					this.SendPropertyChanging();
					this._Creditos_Curso = value;
					this.SendPropertyChanged("Creditos_Curso");
					this.OnCreditos_CursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Carrera", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string Id_Carrera
		{
			get
			{
				return this._Id_Carrera;
			}
			set
			{
				if ((this._Id_Carrera != value))
				{
					if (this._Carrera.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_CarreraChanging(value);
					this.SendPropertyChanging();
					this._Id_Carrera = value;
					this.SendPropertyChanged("Id_Carrera");
					this.OnId_CarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Semestre", DbType="Int NOT NULL")]
		public int Id_Semestre
		{
			get
			{
				return this._Id_Semestre;
			}
			set
			{
				if ((this._Id_Semestre != value))
				{
					if (this._Semestre.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_SemestreChanging(value);
					this.SendPropertyChanging();
					this._Id_Semestre = value;
					this.SendPropertyChanged("Id_Semestre");
					this.OnId_SemestreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Curso_Asigna_Curso", Storage="_Asigna_Cursos", ThisKey="Id_Curso", OtherKey="Id_Curso")]
		public EntitySet<Asigna_Curso> Asigna_Cursos
		{
			get
			{
				return this._Asigna_Cursos;
			}
			set
			{
				this._Asigna_Cursos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Semestre_Curso", Storage="_Semestre", ThisKey="Id_Semestre", OtherKey="Id_Semestre", IsForeignKey=true)]
		public Semestre Semestre
		{
			get
			{
				return this._Semestre.Entity;
			}
			set
			{
				Semestre previousValue = this._Semestre.Entity;
				if (((previousValue != value) 
							|| (this._Semestre.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Semestre.Entity = null;
						previousValue.Cursos.Remove(this);
					}
					this._Semestre.Entity = value;
					if ((value != null))
					{
						value.Cursos.Add(this);
						this._Id_Semestre = value.Id_Semestre;
					}
					else
					{
						this._Id_Semestre = default(int);
					}
					this.SendPropertyChanged("Semestre");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carrera_Curso", Storage="_Carrera", ThisKey="Id_Carrera", OtherKey="Id_Carrera", IsForeignKey=true)]
		public Carrera Carrera
		{
			get
			{
				return this._Carrera.Entity;
			}
			set
			{
				Carrera previousValue = this._Carrera.Entity;
				if (((previousValue != value) 
							|| (this._Carrera.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Carrera.Entity = null;
						previousValue.Cursos.Remove(this);
					}
					this._Carrera.Entity = value;
					if ((value != null))
					{
						value.Cursos.Add(this);
						this._Id_Carrera = value.Id_Carrera;
					}
					else
					{
						this._Id_Carrera = default(string);
					}
					this.SendPropertyChanged("Carrera");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asigna_Cursos(Asigna_Curso entity)
		{
			this.SendPropertyChanging();
			entity.Curso = this;
		}
		
		private void detach_Asigna_Cursos(Asigna_Curso entity)
		{
			this.SendPropertyChanging();
			entity.Curso = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Carrera")]
	public partial class Carrera : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id_Carrera;
		
		private string _Nombre_Carrera;
		
		private bool _Estado_Carrera;
		
		private EntitySet<Curso> _Cursos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_CarreraChanging(string value);
    partial void OnId_CarreraChanged();
    partial void OnNombre_CarreraChanging(string value);
    partial void OnNombre_CarreraChanged();
    partial void OnEstado_CarreraChanging(bool value);
    partial void OnEstado_CarreraChanged();
    #endregion
		
		public Carrera()
		{
			this._Cursos = new EntitySet<Curso>(new Action<Curso>(this.attach_Cursos), new Action<Curso>(this.detach_Cursos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Carrera", DbType="NVarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id_Carrera
		{
			get
			{
				return this._Id_Carrera;
			}
			set
			{
				if ((this._Id_Carrera != value))
				{
					this.OnId_CarreraChanging(value);
					this.SendPropertyChanging();
					this._Id_Carrera = value;
					this.SendPropertyChanged("Id_Carrera");
					this.OnId_CarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Carrera", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Nombre_Carrera
		{
			get
			{
				return this._Nombre_Carrera;
			}
			set
			{
				if ((this._Nombre_Carrera != value))
				{
					this.OnNombre_CarreraChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Carrera = value;
					this.SendPropertyChanged("Nombre_Carrera");
					this.OnNombre_CarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Carrera", DbType="Bit NOT NULL")]
		public bool Estado_Carrera
		{
			get
			{
				return this._Estado_Carrera;
			}
			set
			{
				if ((this._Estado_Carrera != value))
				{
					this.OnEstado_CarreraChanging(value);
					this.SendPropertyChanging();
					this._Estado_Carrera = value;
					this.SendPropertyChanged("Estado_Carrera");
					this.OnEstado_CarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Carrera_Curso", Storage="_Cursos", ThisKey="Id_Carrera", OtherKey="Id_Carrera")]
		public EntitySet<Curso> Cursos
		{
			get
			{
				return this._Cursos;
			}
			set
			{
				this._Cursos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cursos(Curso entity)
		{
			this.SendPropertyChanging();
			entity.Carrera = this;
		}
		
		private void detach_Cursos(Curso entity)
		{
			this.SendPropertyChanging();
			entity.Carrera = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asigna_Curso")]
	public partial class Asigna_Curso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_alum_curso;
		
		private string _Carne;
		
		private string _Id_Curso;
		
		private System.Nullable<int> _Zona;
		
		private System.Nullable<int> _Final;
		
		private System.Nullable<int> _Total;
		
		private string _Literal;
		
		private string _Argumento;
		
		private System.DateTime _fecha_asignacion;
		
		private System.DateTime _fecha_ingreso_nota;
		
		private EntityRef<Curso> _Curso;
		
		private EntityRef<Alumno> _Alumno;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_alum_cursoChanging(int value);
    partial void Onid_alum_cursoChanged();
    partial void OnCarneChanging(string value);
    partial void OnCarneChanged();
    partial void OnId_CursoChanging(string value);
    partial void OnId_CursoChanged();
    partial void OnZonaChanging(System.Nullable<int> value);
    partial void OnZonaChanged();
    partial void OnFinalChanging(System.Nullable<int> value);
    partial void OnFinalChanged();
    partial void OnTotalChanging(System.Nullable<int> value);
    partial void OnTotalChanged();
    partial void OnLiteralChanging(string value);
    partial void OnLiteralChanged();
    partial void OnArgumentoChanging(string value);
    partial void OnArgumentoChanged();
    partial void Onfecha_asignacionChanging(System.DateTime value);
    partial void Onfecha_asignacionChanged();
    partial void Onfecha_ingreso_notaChanging(System.DateTime value);
    partial void Onfecha_ingreso_notaChanged();
    #endregion
		
		public Asigna_Curso()
		{
			this._Curso = default(EntityRef<Curso>);
			this._Alumno = default(EntityRef<Alumno>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_alum_curso", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_alum_curso
		{
			get
			{
				return this._id_alum_curso;
			}
			set
			{
				if ((this._id_alum_curso != value))
				{
					this.Onid_alum_cursoChanging(value);
					this.SendPropertyChanging();
					this._id_alum_curso = value;
					this.SendPropertyChanged("id_alum_curso");
					this.Onid_alum_cursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carne", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Carne
		{
			get
			{
				return this._Carne;
			}
			set
			{
				if ((this._Carne != value))
				{
					if (this._Alumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarneChanging(value);
					this.SendPropertyChanging();
					this._Carne = value;
					this.SendPropertyChanged("Carne");
					this.OnCarneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Curso", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Id_Curso
		{
			get
			{
				return this._Id_Curso;
			}
			set
			{
				if ((this._Id_Curso != value))
				{
					if (this._Curso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_CursoChanging(value);
					this.SendPropertyChanging();
					this._Id_Curso = value;
					this.SendPropertyChanged("Id_Curso");
					this.OnId_CursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zona", DbType="Int")]
		public System.Nullable<int> Zona
		{
			get
			{
				return this._Zona;
			}
			set
			{
				if ((this._Zona != value))
				{
					this.OnZonaChanging(value);
					this.SendPropertyChanging();
					this._Zona = value;
					this.SendPropertyChanged("Zona");
					this.OnZonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Final", DbType="Int")]
		public System.Nullable<int> Final
		{
			get
			{
				return this._Final;
			}
			set
			{
				if ((this._Final != value))
				{
					this.OnFinalChanging(value);
					this.SendPropertyChanging();
					this._Final = value;
					this.SendPropertyChanged("Final");
					this.OnFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Literal", DbType="NVarChar(20)")]
		public string Literal
		{
			get
			{
				return this._Literal;
			}
			set
			{
				if ((this._Literal != value))
				{
					this.OnLiteralChanging(value);
					this.SendPropertyChanging();
					this._Literal = value;
					this.SendPropertyChanged("Literal");
					this.OnLiteralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Argumento", DbType="NVarChar(20)")]
		public string Argumento
		{
			get
			{
				return this._Argumento;
			}
			set
			{
				if ((this._Argumento != value))
				{
					this.OnArgumentoChanging(value);
					this.SendPropertyChanging();
					this._Argumento = value;
					this.SendPropertyChanged("Argumento");
					this.OnArgumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_asignacion", DbType="SmallDateTime NOT NULL")]
		public System.DateTime fecha_asignacion
		{
			get
			{
				return this._fecha_asignacion;
			}
			set
			{
				if ((this._fecha_asignacion != value))
				{
					this.Onfecha_asignacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_asignacion = value;
					this.SendPropertyChanged("fecha_asignacion");
					this.Onfecha_asignacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_ingreso_nota", DbType="SmallDateTime NOT NULL")]
		public System.DateTime fecha_ingreso_nota
		{
			get
			{
				return this._fecha_ingreso_nota;
			}
			set
			{
				if ((this._fecha_ingreso_nota != value))
				{
					this.Onfecha_ingreso_notaChanging(value);
					this.SendPropertyChanging();
					this._fecha_ingreso_nota = value;
					this.SendPropertyChanged("fecha_ingreso_nota");
					this.Onfecha_ingreso_notaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Curso_Asigna_Curso", Storage="_Curso", ThisKey="Id_Curso", OtherKey="Id_Curso", IsForeignKey=true)]
		public Curso Curso
		{
			get
			{
				return this._Curso.Entity;
			}
			set
			{
				Curso previousValue = this._Curso.Entity;
				if (((previousValue != value) 
							|| (this._Curso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Curso.Entity = null;
						previousValue.Asigna_Cursos.Remove(this);
					}
					this._Curso.Entity = value;
					if ((value != null))
					{
						value.Asigna_Cursos.Add(this);
						this._Id_Curso = value.Id_Curso;
					}
					else
					{
						this._Id_Curso = default(string);
					}
					this.SendPropertyChanged("Curso");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumno_Asigna_Curso", Storage="_Alumno", ThisKey="Carne", OtherKey="Carne", IsForeignKey=true)]
		public Alumno Alumno
		{
			get
			{
				return this._Alumno.Entity;
			}
			set
			{
				Alumno previousValue = this._Alumno.Entity;
				if (((previousValue != value) 
							|| (this._Alumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Alumno.Entity = null;
						previousValue.Asigna_Cursos.Remove(this);
					}
					this._Alumno.Entity = value;
					if ((value != null))
					{
						value.Asigna_Cursos.Add(this);
						this._Carne = value.Carne;
					}
					else
					{
						this._Carne = default(string);
					}
					this.SendPropertyChanged("Alumno");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alumno")]
	public partial class Alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Carne;
		
		private string _Nombre1;
		
		private string _Nombre2;
		
		private string _Apellido1;
		
		private string _Apellido2;
		
		private System.Nullable<System.DateTime> _Fecha_Nac;
		
		private string _Celular;
		
		private string _email;
		
		private System.Nullable<bool> _estado;
		
		private EntitySet<Asigna_Curso> _Asigna_Cursos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCarneChanging(string value);
    partial void OnCarneChanged();
    partial void OnNombre1Changing(string value);
    partial void OnNombre1Changed();
    partial void OnNombre2Changing(string value);
    partial void OnNombre2Changed();
    partial void OnApellido1Changing(string value);
    partial void OnApellido1Changed();
    partial void OnApellido2Changing(string value);
    partial void OnApellido2Changed();
    partial void OnFecha_NacChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_NacChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public Alumno()
		{
			this._Asigna_Cursos = new EntitySet<Asigna_Curso>(new Action<Asigna_Curso>(this.attach_Asigna_Cursos), new Action<Asigna_Curso>(this.detach_Asigna_Cursos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carne", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Carne
		{
			get
			{
				return this._Carne;
			}
			set
			{
				if ((this._Carne != value))
				{
					this.OnCarneChanging(value);
					this.SendPropertyChanging();
					this._Carne = value;
					this.SendPropertyChanged("Carne");
					this.OnCarneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre1
		{
			get
			{
				return this._Nombre1;
			}
			set
			{
				if ((this._Nombre1 != value))
				{
					this.OnNombre1Changing(value);
					this.SendPropertyChanging();
					this._Nombre1 = value;
					this.SendPropertyChanged("Nombre1");
					this.OnNombre1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre2", DbType="NVarChar(50)")]
		public string Nombre2
		{
			get
			{
				return this._Nombre2;
			}
			set
			{
				if ((this._Nombre2 != value))
				{
					this.OnNombre2Changing(value);
					this.SendPropertyChanging();
					this._Nombre2 = value;
					this.SendPropertyChanged("Nombre2");
					this.OnNombre2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido1
		{
			get
			{
				return this._Apellido1;
			}
			set
			{
				if ((this._Apellido1 != value))
				{
					this.OnApellido1Changing(value);
					this.SendPropertyChanging();
					this._Apellido1 = value;
					this.SendPropertyChanged("Apellido1");
					this.OnApellido1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido2", DbType="NVarChar(50)")]
		public string Apellido2
		{
			get
			{
				return this._Apellido2;
			}
			set
			{
				if ((this._Apellido2 != value))
				{
					this.OnApellido2Changing(value);
					this.SendPropertyChanging();
					this._Apellido2 = value;
					this.SendPropertyChanged("Apellido2");
					this.OnApellido2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Nac", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Fecha_Nac
		{
			get
			{
				return this._Fecha_Nac;
			}
			set
			{
				if ((this._Fecha_Nac != value))
				{
					this.OnFecha_NacChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Nac = value;
					this.SendPropertyChanged("Fecha_Nac");
					this.OnFecha_NacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="NVarChar(12)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumno_Asigna_Curso", Storage="_Asigna_Cursos", ThisKey="Carne", OtherKey="Carne")]
		public EntitySet<Asigna_Curso> Asigna_Cursos
		{
			get
			{
				return this._Asigna_Cursos;
			}
			set
			{
				this._Asigna_Cursos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asigna_Cursos(Asigna_Curso entity)
		{
			this.SendPropertyChanging();
			entity.Alumno = this;
		}
		
		private void detach_Asigna_Cursos(Asigna_Curso entity)
		{
			this.SendPropertyChanging();
			entity.Alumno = null;
		}
	}
}
#pragma warning restore 1591
